### ISSUE TITLE
Getting error messages in R when using the sliders

### ISSUE THREAD

**Issue by 30-06** [Huh/Risk-Assessment#1]
When using the sliders, I am getting the following error messages...I don't know if it is because alpha/beta are <=0 or something of that nature.  It looks like you already have the following constraints: mu should be in the interval 0-1, and therefore the bounds for the variance 0<=var<0.25.

Listening on http://127.0.0.1:4433
Error in user_vals[i] <- as.numeric(input[[paste0("txt", i)]]) : 
  replacement has length zero
Error in user_vals[i] <- as.numeric(input[[paste0("txt", i)]]) : 
  replacement has length zero
Warning in rbeta(30000, beta_parms$alpha, beta_parms$beta) :
  NAs produced
Warning: Removed 30000 rows containing non-finite values (stat_density).
Error in exists(name, envir = env, mode = mode) : 
  argument "env" is missing, with no default
Error in quantile.default(dat_in$dat$val, 0.025) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE
Error in quantile.default(dat_in$dat$val, 0.5) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE
Error in quantile.default(dat_in$dat$val, 0.975) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE
Warning in rbeta(30000, beta_parms$alpha, beta_parms$beta) :
  NAs produced
Warning: Removed 30000 rows containing non-finite values (stat_density).
Error in exists(name, envir = env, mode = mode) : 
  argument "env" is missing, with no default
Error in quantile.default(dat_in$dat$val, 0.025) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE
Error in quantile.default(dat_in$dat$val, 0.5) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE
Error in quantile.default(dat_in$dat$val, 0.975) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE

**Comment by Huh** [comment]
Yeah, that is just part of the reactive bit and is largely a timing issue where the operations occur out of order, but it does not influence the actual behavior of the app.  I can go looking for a fix later, but this seems inconsequential for the moment.

**Comment by 30-06** [comment]
Okay, that makes sense.

**Comment by Huh** [comment]
Should be fixed now.
