### ISSUE TITLE
changing mu/var

### ISSUE THREAD

**Issue by 30-06** [Huh/Risk-Assessment#2]
For the continuous distribution, can we add more significant digits for the variance...particularly the lower end.  Right now you can get the variance of the mean below 0.005, which still leaves a wide spread.  I am thinking maybe 0.000005, which will allow +/- 0.05 on the probability scale.  And can the mu slider be at 0.05 increments for a little bit finer resolution?

**Comment by Huh** [comment]
Did you change this comment?  So, to answer the first about how the SD slider changes in response to the mu, it has to or it will provide inappropriate values to the beta and I know it is not great.  I tend to think working from left to right makes the most sense, but am open to ideas.

I will change the precision of the values.

**Comment by Huh** [comment]
Done.  

I also changed the range of the mu slider to 0.05 - 0.95.  The distribution behaves strangely at the boundaries using this parameterization.

**Comment by Huh** [comment]
Close if you are satisfied

**Comment by 30-06** [comment]
Yes, I changed the comment after playing around with it more and looking at the code.  I think this looks good.
