### ISSUE TITLE
discrete distribution

### ISSUE THREAD

**Issue by 30-06** [Huh/Risk-Assessment#3]
Can the warning of summing to be 20 disappear once the user's sum = 20?  

I am thinking maybe if we just display the user's values rather than the results of  the sample function, it would be best.  It would make the boxes all line up then if they are the same value, and the y axis could then be scaled to the user's input.  But, we could store the probabilities in the database for further manipulation behind the scenes.

**Comment by Huh** [comment]
Done

**Comment by Huh** [comment]
Close if you are satisfied.

**Comment by 30-06** [comment]
Looks good.
